#!/usr/bin/env python3
"""Generate self-contained task setup resources from the canonical JishuDB Skill."""

from __future__ import annotations

import argparse
import hashlib
from importlib import import_module
import json
from pathlib import Path
import re

# Reuse the existing distribution renderer, including its checked macOS path rewrite.
distribution = import_module("package-jishudb-skillhub")
REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
BUNDLE_PATH = Path("references/jishudb-setup")


def bundle_files() -> dict[str, tuple[bytes, int]]:
    """Render a pinned copy without registering a second, nested Skill entrypoint."""
    files = distribution.build_files()
    skill, _ = files.pop("SKILL.md")
    source = skill.decode("utf-8")
    frontmatter = re.match(r"\A---\n(.*?)\n---\n", source, re.DOTALL)
    if not frontmatter:
        raise ValueError("Canonical setup Skill has no frontmatter")
    version = re.search(r'^  version: "([0-9]+\.[0-9]+\.[0-9]+)"$', frontmatter[1], re.MULTILINE)
    if not version:
        raise ValueError("Canonical setup Skill has no version")
    note = (
        "<!-- Generated by scripts/bundle-task-setup.py; edit skills/jishudb instead. -->\n\n"
        "This setup guide and its helpers are included in the current task Skill.\n"
        "No separate Skill installation or marketplace download is needed. Resolve\n"
        "all relative resource paths and run helper commands from this guide's\n"
        "directory, using its absolute path if the host does not preserve cwd.\n"
        "Follow the installation contract before running a helper. After actual\n"
        "client/runtime readiness, return to the calling task. Task installation\n"
        "does not grant Desktop installation, write privileges, or user consent.\n\n"
    )
    recovery, mode = files["references/connection-recovery.md"]
    files["references/connection-recovery.md"] = (recovery.replace(b"`SKILL.md`", b"[setup guide](../setup.md)"), mode)
    files["setup.md"] = ((note + source[frontmatter.end():].lstrip()).encode(), 0o644)
    manifest = {
        "schemaVersion": 1,
        "sourceSkill": "jishudb",
        "sourceVersion": version[1],
        "generator": "scripts/bundle-task-setup.py",
        "files": [
            {"path": name, "sha256": hashlib.sha256(data).hexdigest(), "mode": f"{mode:03o}"}
            for name, (data, mode) in sorted(files.items())
        ],
    }
    files["bundle-manifest.json"] = ((json.dumps(manifest, indent=2) + "\n").encode(), 0o644)
    return files


def task_roots(repository: Path) -> list[Path]:
    """Select packages explicitly opting into the shared setup bundle."""
    return [
        entry.parent for entry in sorted((repository / "skills").glob("*/SKILL.md"))
        if re.search(r'^  bundled-setup: jishudb$', entry.read_text(encoding="utf-8"), re.MULTILINE)
    ]


def synchronize(task: Path, files: dict[str, tuple[bytes, int]], *, check: bool) -> None:
    """Write or verify owned files; reject symlinks and unexpected bundle content."""
    destination = task / BUNDLE_PATH
    for parent in (task, task / "references", destination):
        if parent.is_symlink():
            raise ValueError(f"Refusing symlink: {parent}")
    if destination.exists():
        actual = set()
        for entry in destination.rglob("*"):
            if entry.is_symlink() or not (entry.is_dir() or entry.is_file()):
                raise ValueError(f"Unsupported bundle entry: {entry}")
            if entry.is_file():
                actual.add(entry.relative_to(destination).as_posix())
        if actual - files.keys():
            raise ValueError(f"Unexpected files in {destination}: {sorted(actual - files.keys())}")
    for relative, (data, mode) in sorted(files.items()):
        output = destination / relative
        if check:
            if not output.is_file() or output.read_bytes() != data:
                raise ValueError(f"Stale or missing setup resource: {output}; run npm run bundle:setup")
        else:
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_bytes(data)
            output.chmod(mode)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    files = bundle_files()
    targets = task_roots(REPOSITORY_ROOT)
    if not targets:
        raise ValueError("No task Skill opts into bundled setup")
    for task in targets:
        synchronize(task, files, check=args.check)
    print(f"{'Verified' if args.check else 'Generated'} setup bundles for {len(targets)} task Skills")


if __name__ == "__main__":
    main()
